Support filtering by has_many associations, without having to specify a custom filter
fluxfederation/partial_ks pull request #7
Opened 2017-01-28 19:41 UTC by kuahyeow

2017-01-28 19:44 UTC, kuahyeow commented on test/table_test.rb
> +  describe "#" do
ooops

2017-01-28 19:44 UTC, kuahyeow commented on test/table_test.rb
> +      PostTag.stub :pluck, [post_tag_id] do    # TODO verify the pluck
Ahem, TODO

2017-01-28 19:44 UTC, kuahyeow commented on test/table_test.rb
> +        table.relation_for_association(OldEntry).to_sql.must_equal "SELECT \"old_tags\".* FROM \"old_tags\" WHERE \"old_tags\".\"blog_post_id\" = 0"
These SELECT queries feel quite brittle. No good ideas as to alternatives currently but it does lock one into the vagaries of how ActiveRecord emits SQL statements. Is a small hassle to update tests, is all

2017-02-01 21:07 UTC, dylanmckay commented
Nice change!

I've left two minor suggestions, otherwise looks good to me!

2017-02-02 07:32 UTC, kuahyeow commented
Thanks ! Hmm, I can't see those suggestions @dylanmckay

2017-02-02 21:12 UTC, dylanmckay commented
Ah, I'm not used to GitHub's review feature. Should be up now.

2017-02-02 21:13 UTC, dylanmckay requested changes

2017-02-02 21:13 UTC, dylanmckay commented on test/table_test.rb
> +        table.relation_for_association(User).must_equal BlogPost.where(:user_id => [0] + user_ids)
Nit: you use hash rockets here but the newer syntax further up the diff

2017-02-02 21:13 UTC, dylanmckay commented on lib/partial_ks/table.rb
> +    def relation_for_association(klass)
`relation_for_association` strongly implies it takes an `ActiveRecord::Relation`, but it actually takes a model and deduces the association from it.

Perhaps `relation_for_associated_model` could be more suitable?

2017-02-03 07:37 UTC, kuahyeow commented on lib/partial_ks/table.rb
> +    def relation_for_association(klass)
That's a perfect name! will change.

2017-02-03 07:53 UTC, kuahyeow commented on test/table_test.rb
> +        table.relation_for_association(User).must_equal BlogPost.where(:user_id => [0] + user_ids)
Hmm, looks like I use hash rockets everywhere prior to this change, but where I use `:` it's used for passing in keyword arguments. I would suggest fixing any consistency if any, later ?

2017-02-03 08:00 UTC, dylanmckay commented on test/table_test.rb
> +        table.relation_for_association(User).must_equal BlogPost.where(:user_id => [0] + user_ids)
Sounds good to me

2017-02-03 08:02 UTC, dylanmckay approved these changes
Nice work!

2017-02-03 08:03 UTC, merged